apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a82231835 # 이 이름이 URL의 컴포넌트 이름과 일치해야 합니다.
  description: a82231835 프로젝트의 Backstage 카탈로그
  owner: sunghwan-joo
  annotations:
      backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: sunghwan-joo
  providesApis:
      - default/hello-world  # API 엔터티와 연결
  dependsOn:
      - resource:default/database  # 의존하고 있는 리소스 정의
      - component:default/api-service  # 의존하고 있는 컴포넌트 정의