apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a82231835 # 이 이름이 URL의 컴포넌트 이름과 일치해야 합니다.
  description: a82231835 프로젝트의 Backstage 카탈로그
  owner: platform_CoE_Team
  annotations:
      backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: platform_CoE_Team
  providesApis:
    - used-api
  consumesApis:
    - hello-world-api
  dependsOn:
     - api:default/hello-world-api  # 의존하는 API 정의
     - api:default/used-api          # 의존하는 API 정의
     - component:default/my-service   # 의존하는 서비스 정의
     - resource:default/project-database
