site_name: "a82231835"
nav:
  - Home: index.md
  - Download Example: examples/download.md
  - Iframe Example: examples/iframe.md
  - Lists Example: examples/lists.md
  - Mermaid Example: examples/mermaid.md
  - Plantuml Example: examples/plantuml.md
plugins:
  - techdocs-core
