site_name: "a82231835"
nav:
  - Home: index.md
  - Download Example: examples/download.md
  - Iframe Example: examples/iframe.md
  - Lists Example: examples/lists.md
  - Mermaid Example: examples/mermaid.md
docs_dir: /docs
plugins:
  - techdocs-core
markdown_extensions:
  - admonition  # 추가할 Markdown 확장