apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hello-world
  description: A simple API that returns a greeting
spec:
  type: openapi  # API 타입 (openapi, grpc, graphql 등)
  lifecycle: production
  owner: platform_CoE_Team  # API의 소유자 팀 또는 개인
  definition: |
    openapi: 3.0.0
    info:
      title: Hello World API
      version: 1.0.0
    paths:
      /hello:
        get:
          summary: Returns a greeting.
          responses:
            '200':
              description: A greeting.
              content:
                application/json:
                  schema:
                    type: string
